typography_spectrum: 0.9955693103838712
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9913418868090957
  lightness: 0.00801684451289475
  saturation: 0.7086226281244308
  rhythmicContrast: 0.3877067877911031
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1820854356046766
analytics:
  google: null
  facebook: null
  twitter: null
name: Everett Griffiths
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Masterminding in the Genius Room
content: []
purpose: []
url: 'http://everettgriffiths.com'
description: somnambulating thoughts
